"""Versão inicial do banco de dados

Revision ID: 04fe39e91cfb
Revises: 
Create Date: 2025-08-09 21:54:11.734549

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '04fe39e91cfb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('motoristas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('login', sa.String(length=50), nullable=False),
    sa.Column('senha_hash', sa.String(length=500), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('transportadora',
    sa.Column('codfornecfrete', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('api_identifier', sa.String(length=50), nullable=True),
    sa.Column('api_config_key', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('codfornecfrete'),
    sa.UniqueConstraint('api_config_key')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('login', sa.String(length=50), nullable=False),
    sa.Column('senha_hash', sa.String(length=256), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('entregas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('CODFILIAL', sa.Integer(), nullable=False),
    sa.Column('DTFAT', sa.DateTime(), nullable=False),
    sa.Column('DTCARREGAMENTO', sa.DateTime(), nullable=False),
    sa.Column('ROMANEIO', sa.Integer(), nullable=False),
    sa.Column('TIPOVENDA', sa.Integer(), nullable=False),
    sa.Column('NUMNOTA', sa.Integer(), nullable=False),
    sa.Column('NUMPED', sa.Integer(), nullable=False),
    sa.Column('CODCLI', sa.Integer(), nullable=False),
    sa.Column('CLIENTE', sa.String(length=200), nullable=False),
    sa.Column('MUNICIPIO', sa.String(length=50), nullable=False),
    sa.Column('UF', sa.String(length=2), nullable=False),
    sa.Column('EMAIL', sa.String(length=100), nullable=True),
    sa.Column('TELCOM', sa.String(length=20), nullable=True),
    sa.Column('EMAIL_1', sa.String(length=100), nullable=True),
    sa.Column('TRANSPORTADORA', sa.String(length=200), nullable=False),
    sa.Column('VLTOTAL', sa.Float(precision=10, asdecimal=2), nullable=False),
    sa.Column('NUMVOLUME', sa.Integer(), nullable=False),
    sa.Column('TOTPESO', sa.Float(precision=10, asdecimal=2), nullable=False),
    sa.Column('PRAZOENTREGA', sa.Integer(), nullable=False),
    sa.Column('CHAVENFE', sa.String(length=44), nullable=False),
    sa.Column('PREVISAOENTREGA', sa.DateTime(), nullable=True),
    sa.Column('DATAFINALIZACAO', sa.DateTime(), nullable=True),
    sa.Column('STATUS', postgresql.ENUM('ENTREGA_PENDENTE', 'ENTREGUE_AGUARDANDO_COMPROVANTE', 'ENTREGA_FINALIZADA', 'DEVOLUCAO_PARCIAL', 'DEVOLUCAO_TOTAL', name='entregas_status_enum'), nullable=False),
    sa.Column('DIASATRASO', sa.Integer(), nullable=True),
    sa.Column('PRAZOMEDIO', sa.Integer(), nullable=True),
    sa.Column('AGENDAMENTO', sa.DateTime(), nullable=True),
    sa.Column('DEVOLUCAO', sa.Boolean(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=False),
    sa.Column('CODFORNECFRETE', sa.Integer(), nullable=True),
    sa.Column('motorista_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['CODFORNECFRETE'], ['transportadora.codfornecfrete'], ),
    sa.ForeignKeyConstraint(['motorista_id'], ['motoristas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comprovantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entrega_id', sa.Integer(), nullable=False),
    sa.Column('motorista_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('caminho_arquivo', sa.String(length=255), nullable=False),
    sa.Column('data_envio', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entrega_id'], ['entregas.id'], ),
    sa.ForeignKeyConstraint(['motorista_id'], ['motoristas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devolucoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entrega_id', sa.Integer(), nullable=False),
    sa.Column('motorista_id', sa.Integer(), nullable=False),
    sa.Column('tipo_devolucao', sa.String(length=20), nullable=True),
    sa.Column('motivo', sa.String(length=255), nullable=True),
    sa.Column('observacoes', sa.String(length=500), nullable=True),
    sa.Column('data_devolucao', sa.DateTime(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['entrega_id'], ['entregas.id'], ),
    sa.ForeignKeyConstraint(['motorista_id'], ['motoristas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rastreamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('status_descricao', sa.String(length=200), nullable=False),
    sa.Column('localizacao', sa.String(length=150), nullable=True),
    sa.Column('entrega_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entrega_id'], ['entregas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rastreamento')
    op.drop_table('devolucoes')
    op.drop_table('comprovantes')
    op.drop_table('entregas')
    op.drop_table('usuarios')
    op.drop_table('transportadora')
    op.drop_table('motoristas')
    # ### end Alembic commands ###
