"""Adiciona campos de agendamento e auditoria

Revision ID: 24eee94bce79
Revises: 98851bde219b
Create Date: 2025-08-10 19:08:15.760402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24eee94bce79'
down_revision = '98851bde219b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entregas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agendamento_motivo', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('ultimo_usuario_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_entregas_ultimo_usuario_id_usuarios'), 'usuarios', ['ultimo_usuario_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entregas', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_entregas_ultimo_usuario_id_usuarios'), type_='foreignkey')
        batch_op.drop_column('ultimo_usuario_id')
        batch_op.drop_column('agendamento_motivo')

    # ### end Alembic commands ###
