"""Adicionar tabelas Motorista, Comprovante e Devolucao

Revision ID: 29ed83ffa8f7
Revises: 68e313ea5a79
Create Date: 2025-07-19 20:48:14.783051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29ed83ffa8f7'
down_revision = '68e313ea5a79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comprovantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entrega_id', sa.Integer(), nullable=False),
    sa.Column('motorista_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('caminho_arquivo', sa.String(length=255), nullable=False),
    sa.Column('data_envio', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entrega_id'], ['entregas.id'], ),
    sa.ForeignKeyConstraint(['motorista_id'], ['motoristas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devolucoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entrega_id', sa.Integer(), nullable=False),
    sa.Column('motorista_id', sa.Integer(), nullable=False),
    sa.Column('tipo_devolucao', sa.String(length=20), nullable=True),
    sa.Column('motivo', sa.String(length=255), nullable=True),
    sa.Column('observacoes', sa.DateTime(), nullable=False),
    sa.Column('data_devolucao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entrega_id'], ['entregas.id'], ),
    sa.ForeignKeyConstraint(['motorista_id'], ['motoristas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entregas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('motorista_id', sa.Integer(), nullable=False))
        batch_op.alter_column('VLTOTAL',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=2),
               existing_nullable=False)
        batch_op.alter_column('TOTPESO',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=2),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'motoristas', ['motorista_id'], ['id'])

    with op.batch_alter_table('motoristas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('login', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('senha_hash', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('data_criacao', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('data_atualizacao', sa.DateTime(), nullable=True))
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['login'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('motoristas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('nome',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('data_atualizacao')
        batch_op.drop_column('data_criacao')
        batch_op.drop_column('senha_hash')
        batch_op.drop_column('login')

    with op.batch_alter_table('entregas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('TOTPESO',
               existing_type=sa.Float(precision=10, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('VLTOTAL',
               existing_type=sa.Float(precision=10, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.drop_column('motorista_id')

    op.drop_table('devolucoes')
    op.drop_table('comprovantes')
    # ### end Alembic commands ###
