"""Adiciona status ENTREGUE_AGUARDANDO_COMPROVANTE

Revision ID: 82040121aba3
Revises: 3a936a2f5343
Create Date: 2025-08-02 20:39:32.139949

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '82040121aba3'
down_revision = '3a936a2f5343'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entregas', schema=None) as batch_op:
        batch_op.alter_column('VLTOTAL',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=2),
               existing_nullable=False)
        batch_op.alter_column('TOTPESO',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=2),
               existing_nullable=False)
        batch_op.alter_column('PREVISAOENTREGA',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('STATUS',
               existing_type=sa.VARCHAR(length=20),
               type_=postgresql.ENUM('ENTREGA_PENDENTE', 'ENTREGUE_AGUARDANDO_COMPROVANTE', 'ENTREGA_FINALIZADA', 'DEVOLUCAO_PARCIAL', 'DEVOLUCAO_TOTAL', name='entregas_status_enum'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entregas', schema=None) as batch_op:
        batch_op.alter_column('STATUS',
               existing_type=postgresql.ENUM('ENTREGA_PENDENTE', 'ENTREGUE_AGUARDANDO_COMPROVANTE', 'ENTREGA_FINALIZADA', 'DEVOLUCAO_PARCIAL', 'DEVOLUCAO_TOTAL', name='entregas_status_enum'),
               type_=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('PREVISAOENTREGA',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('TOTPESO',
               existing_type=sa.Float(precision=10, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('VLTOTAL',
               existing_type=sa.Float(precision=10, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
