"""Corrige a estrutura da tabela Entrega

Revision ID: 98851bde219b
Revises: 04fe39e91cfb
Create Date: 2025-08-10 12:21:41.913829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98851bde219b'
down_revision = '04fe39e91cfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entregas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('VENDEDOR', sa.String(length=100), nullable=True))

    with op.batch_alter_table('rastreamento', schema=None) as batch_op:
        batch_op.alter_column('entrega_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rastreamento', schema=None) as batch_op:
        batch_op.alter_column('entrega_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('entregas', schema=None) as batch_op:
        batch_op.drop_column('VENDEDOR')

    # ### end Alembic commands ###
