"""Adicionar coluna 'status' ao modelo Devolucao

Revision ID: 9f3e964c8443
Revises: cecbb178a889
Create Date: 2025-07-22 10:48:11.021236

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text

# revision identifiers, used by Alembic.
revision = '9f3e964c8443'
down_revision = 'cecbb178a889'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('login', sa.String(length=50), nullable=False),
    sa.Column('senha_hash', sa.String(length=128), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    with op.batch_alter_table('devolucoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(20), nullable=True))
    op.execute(
        text("UPDATE devolucoes SET status = 'ativa' WHERE status IS NULL")
    )

    with op.batch_alter_table('devolucoes', schema=None) as batch_op:
        # 3. Altere a coluna 'status' para ser NOT NULL
        batch_op.alter_column('status',
                   existing_type=sa.String(20),
                   nullable=False)


    with op.batch_alter_table('entregas', schema=None) as batch_op:
        batch_op.alter_column('VLTOTAL',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=2),
               existing_nullable=False)
        batch_op.alter_column('TOTPESO',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entregas', schema=None) as batch_op:
        batch_op.alter_column('TOTPESO',
               existing_type=sa.Float(precision=10, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('VLTOTAL',
               existing_type=sa.Float(precision=10, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('devolucoes', schema=None) as batch_op:
        batch_op.drop_column('status')

    op.drop_table('usuarios')
    # ### end Alembic commands ###
