"""Atualizar modelo Entrega com novos campos

Revision ID: b2ec09a46ce7
Revises: 7a2a45cb6e81
Create Date: 2025-07-20 01:26:48.922662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2ec09a46ce7'
down_revision = '7a2a45cb6e81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entregas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_criacao', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('data_atualizacao', sa.DateTime(), nullable=False))
        batch_op.alter_column('VLTOTAL',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=2),
               existing_nullable=False)
        batch_op.alter_column('TOTPESO',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entregas', schema=None) as batch_op:
        batch_op.alter_column('TOTPESO',
               existing_type=sa.Float(precision=10, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('VLTOTAL',
               existing_type=sa.Float(precision=10, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.drop_column('data_atualizacao')
        batch_op.drop_column('data_criacao')

    # ### end Alembic commands ###
