"""Recrear tabela devolucoes com observacoes como string

Revision ID: f13d509642e3
Revises: 207c30a9d4c4
Create Date: 2025-07-20 19:19:08.606358

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f13d509642e3'
down_revision = '207c30a9d4c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devolucoes', schema=None) as batch_op:
        batch_op.alter_column('observacoes',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(length=500),
               nullable=True)

    with op.batch_alter_table('entregas', schema=None) as batch_op:
        batch_op.alter_column('VLTOTAL',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=2),
               existing_nullable=False)
        batch_op.alter_column('TOTPESO',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entregas', schema=None) as batch_op:
        batch_op.alter_column('TOTPESO',
               existing_type=sa.Float(precision=10, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('VLTOTAL',
               existing_type=sa.Float(precision=10, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('devolucoes', schema=None) as batch_op:
        batch_op.alter_column('observacoes',
               existing_type=sa.String(length=500),
               type_=postgresql.TIMESTAMP(),
               nullable=False)

    # ### end Alembic commands ###
